config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'orders#new'
  resources :orders, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :price, presence: true, numericality: true
  validates :total, presence: true, numericality: true
  validates :quantity, presence: true, numericality: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items
  accepts_nested_attributes_for :line_items, reject_if: :all_blank

  validates :customer_name, presence: true
  validates :customer_address, presence: true
  validates :total_price, presence: true, numericality: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_one :promotion, class_name: 'ProductsPromotion'

  def has_promotion?
    product_promotion.present?
  end
end

app/models/products_promotion.rb
class ProductsPromotion < ApplicationRecord
  belongs_to :product
  belongs_to :freebie_product, class_name: 'Product', optional: true

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    load_products
    @order = Order.new
  end

  def create
    ActiveRecord::Base.transaction do
      create_order
      create_line_items
      apply_promotions
      compute_order_total
    end

    redirect_to @order, notice: 'Order was successfully created.'
  end

  def show
    load_order
  end

  private

  def create_order
    @order = Order.new
    @order.customer_name = order_params[:customer_name]
    @order.customer_address = order_params[:customer_address]
    @order.total_price = 0
    @order.save
  end

  def create_line_items
    line_item_params = order_params[:line_items_attributes]
    line_items = LineItems::BuildParams.call(line_item_params)

    line_items.each do |line_item|
      LineItems::Create.call(@order, line_item)
    end
  end

  def compute_order_total
    @order.reload
    Orders::UpdateTotal.call(@order)
  end

  def apply_promotions
    line_items = @order.line_items

    line_items.each do |line_item|
      product = line_item.product
      LineItems::ComputePromotion.call(product, line_item)
    end
  end

  def load_products
    @products ||= Product.all
  end

  def load_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:customer_name, :customer_address, line_items_attributes: [:product_id, :quantity])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b>
    0.1
  </div>
  First Circle 2021
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="<%= root_url %>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">
      <b>F</b>Circle</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">
      <b>First Circle</b>
    </span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">

  </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li>
        <a href="<%= new_order_path %>">
          <i class="fa fa-shopping-cart"></i>
          <span>New Order</span>
        </a>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstCircleChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "toastr.css" %>
    <%= stylesheet_link_tag "AdminLTE.min.css" %>
    <%= stylesheet_link_tag "admin-lte-all-skins.min.css" %>
    <%= stylesheet_link_tag "blue.css" %>
    <%= stylesheet_link_tag "dataTables.bootstrap.css" %>
    <%= stylesheet_link_tag "datepicker3.css" %>

    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" %>
    <%= javascript_include_tag "https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"%>
    <%= javascript_include_tag "toastr.min.js" %>
    <%= javascript_include_tag "bootstrap3-wysihtml5.all.min.js"%>
    <%= javascript_include_tag "jquery.dataTables.min.js"%>
    <%= javascript_include_tag "dataTables.bootstrap.min.js"%>
    <%= javascript_include_tag "jquery.slimscroll.min.js"%>
    <%= javascript_include_tag "fastclick.js"%>
    <%= javascript_include_tag "admin-lte-app.min.js"%>
    <%= javascript_include_tag "icheck.min.js"%>
    <%= javascript_include_tag "bootstrap-datepicker.js"%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-10 col-md-offset-1">
            <!-- general form elements -->
            <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">New Order</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%= form_for @order do |f| %>
                <% if @order.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@order.errors.count, 'error') %> prohibited this item from being saved:</h2>
                    <ul>
                      <% @order.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="box-body" width="100%">
                  <div class="form-group">
                    <label>Customer's Name</label>
                    <%= f.text_field :customer_name, autocomplete: "off", placeholder: "Enter Customer's Name", class: "form-control", required: true %>
                  </div>
                  <div class="form-group">
                    <label>Customer's Address</label>
                    <%= f.text_area :customer_address, class: "form-control", rows: "3", laceholder: "Enter Customer's Address"%>
                  </div>
                  <div id="line-item-fields">
                    <div class="row">
                      <div class="col-md-10">
                        <h4> Line Items </h4>
                      </div>
                      <div class="col-md-2 col-md-offset-10">
                        <%= f.add_nested_fields_link :line_items, '', class: 'btn btn-primary fa fa-plus pull-right', role: 'button' %>
                      </div>
                    </div>
                    <br>
                    <%= f.nested_fields_for :line_items do |line_item| %>
                      <%= render partial: 'orders/new/line_item_field', locals: { line_item: line_item, products: @products} %>
                    <% end %>
                  </div>
                </div>

                <%= f.number_field :item_id, :value => params[:item], :hidden => true %>

                <!-- /.box-body -->
                <div class="box-footer">
                  <%= f.submit 'Submit', class: 'btn btn-primary' %>
                </div>
              <% end %>
            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <%= render 'layouts/footer' %>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $(document).ready(function () {
        $.widget.bridge('uibutton', $.ui.button);
        $('.datepicker').datepicker({format: 'yyyy/mm/dd'});
      });
    </script>
  </div>
</body>

app/views/orders/new/_line_item_field.html.erb
<div class="row">
  <div class="col-sm-4">
    <div class="form-group">
      <label>Product</label>
      <%= line_item.select(:product_id, options_from_collection_for_select(products, 'id', 'name'), { include_blank: true }, { class: 'form-control', required: true }) %>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="form-group">
      <label>Quantity</label>
      <%= line_item.number_field :quantity, class: 'form-control', placeholder: 'Enter Quantity', required: true %>
    </div>
  </div>
  <div class="col-sm-2">
    <br>
    <%= line_item.remove_nested_fields_link '', class: 'btn btn-danger fa fa-minus', role: 'button' %>
  </div>
</div>

app/views/orders/show.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-10 col-md-offset-1">
            <!-- general form elements -->
            <div class="box box-header">
              <div class="box-header with-border">
                <h2 class="box-title">Order Details</h2>
              </div>

              <%= render partial: 'orders/show/details', locals: { order: @order } %>

            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <%= render 'layouts/footer' %>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $(document).ready(function () {
        $.widget.bridge('uibutton', $.ui.button);
        $('.datepicker').datepicker({format: 'yyyy/mm/dd'});
      });
    </script>
  </div>
</body>

app/views/orders/show/_details.html.erb
<%
  line_items = order.line_items
%>

<div class='box-body'>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <span id="customer-name"> Customer Name: <%= order.customer_name %> </span>
    </div>
    <div class="col-md-4">
      <span id="customer-address"> Customer Address: <%= order.customer_address %> </span>
    </div>
  </div>
  <hr/>
  <%= render partial: 'orders/show/line_items', locals: { order: order, line_items: line_items } %>
  <%= render partial: 'orders/show/total', locals: { order: order } %>
</div>

app/views/orders/show/_line_items.html.erb
<div class="row">
  <div class="col-md-4">
    <h5> Line Items: </h5>
  </div>
</div>

<table class="table table-sm">
  <thead>
    <tr>
      <td> Quantity </td>
      <td> Product </td>
      <td> Price </td>
    </tr>
  </thead>
  <tbody>
    <% line_items.each do |line_item| %>
      <%
        product = line_item.product
        product_name = product.name
      %>

      <tr>
        <td> <%= line_item.quantity %> </td>
        <td> <%= product_name %> (<%= line_item.price %>)</td>
        <td> <%= line_item.total %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/show/_total.html.erb
<div class="box-footer">
  <span class="pull-right">
    <strong> Total: </strong>
    <%= number_to_currency(order.total_price) %>
  </span>
</div>